use gpui::{App, KeyBinding, actions};

actions!(
    ariadeck,
    [
        Backspace,
        Delete,
        MoveLeft,
        MoveRight,
        SelectLeft,
        SelectRight,
        InsertNewline,
        SelectAll,
        SelectAllTasks,
        MoveHome,
        MoveEnd,
        Paste,
        Cut,
        Copy,
        FocusSearch,
        ClearSearch,
        SelectNextTask,
        SelectPreviousTask,
        OpenAddDownload,
        CloseAddDownload,
        SubmitAddDownload,
        OpenTaskDetails,
        OpenSettings,
        CloseSettings,
        SaveSettings,
        PauseSelectedTask,
        ResumeSelectedTask,
        RetrySelectedTask,
        OpenTaskOutputName,
        CloseTaskOutputName,
        SubmitTaskOutputName,
        CloseBatchFailures,
        RemoveSelectedTask,
        FocusNext,
        FocusPrevious,
    ]
);

pub fn init(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("backspace", Backspace, Some("SearchInput")),
        KeyBinding::new("delete", Delete, Some("SearchInput")),
        KeyBinding::new("left", MoveLeft, Some("SearchInput")),
        KeyBinding::new("right", MoveRight, Some("SearchInput")),
        KeyBinding::new("shift-left", SelectLeft, Some("SearchInput")),
        KeyBinding::new("shift-right", SelectRight, Some("SearchInput")),
        KeyBinding::new("secondary-a", SelectAll, Some("SearchInput")),
        KeyBinding::new("home", MoveHome, Some("SearchInput")),
        KeyBinding::new("end", MoveEnd, Some("SearchInput")),
        KeyBinding::new("secondary-v", Paste, Some("SearchInput")),
        KeyBinding::new("secondary-x", Cut, Some("SearchInput")),
        KeyBinding::new("secondary-c", Copy, Some("SearchInput")),
        KeyBinding::new("backspace", Backspace, Some("AddDownloadInput")),
        KeyBinding::new("delete", Delete, Some("AddDownloadInput")),
        KeyBinding::new("left", MoveLeft, Some("AddDownloadInput")),
        KeyBinding::new("right", MoveRight, Some("AddDownloadInput")),
        KeyBinding::new("shift-left", SelectLeft, Some("AddDownloadInput")),
        KeyBinding::new("shift-right", SelectRight, Some("AddDownloadInput")),
        KeyBinding::new("shift-enter", InsertNewline, Some("AddDownloadInput")),
        KeyBinding::new("secondary-a", SelectAll, Some("AddDownloadInput")),
        KeyBinding::new("home", MoveHome, Some("AddDownloadInput")),
        KeyBinding::new("end", MoveEnd, Some("AddDownloadInput")),
        KeyBinding::new("secondary-v", Paste, Some("AddDownloadInput")),
        KeyBinding::new("secondary-x", Cut, Some("AddDownloadInput")),
        KeyBinding::new("secondary-c", Copy, Some("AddDownloadInput")),
        KeyBinding::new("backspace", Backspace, Some("OutputNameInput")),
        KeyBinding::new("delete", Delete, Some("OutputNameInput")),
        KeyBinding::new("left", MoveLeft, Some("OutputNameInput")),
        KeyBinding::new("right", MoveRight, Some("OutputNameInput")),
        KeyBinding::new("shift-left", SelectLeft, Some("OutputNameInput")),
        KeyBinding::new("shift-right", SelectRight, Some("OutputNameInput")),
        KeyBinding::new("secondary-a", SelectAll, Some("OutputNameInput")),
        KeyBinding::new("home", MoveHome, Some("OutputNameInput")),
        KeyBinding::new("end", MoveEnd, Some("OutputNameInput")),
        KeyBinding::new("secondary-v", Paste, Some("OutputNameInput")),
        KeyBinding::new("secondary-x", Cut, Some("OutputNameInput")),
        KeyBinding::new("secondary-c", Copy, Some("OutputNameInput")),
        KeyBinding::new("cmd-f", FocusSearch, None),
        KeyBinding::new("secondary-a", SelectAllTasks, Some("DownloadWorkspace")),
        KeyBinding::new("cmd-n", OpenAddDownload, Some("DownloadWorkspace")),
        KeyBinding::new("escape", CloseAddDownload, Some("AddDownloadDialog")),
        KeyBinding::new("enter", SubmitAddDownload, Some("AddDownloadDialog")),
        KeyBinding::new("cmd-enter", SubmitAddDownload, Some("AddDownloadDialog")),
        KeyBinding::new("escape", ClearSearch, Some("SearchInput")),
        KeyBinding::new("escape", ClearSearch, Some("DownloadWorkspace")),
        KeyBinding::new("down", SelectNextTask, Some("DownloadWorkspace")),
        KeyBinding::new("up", SelectPreviousTask, Some("DownloadWorkspace")),
        KeyBinding::new("enter", OpenTaskDetails, Some("DownloadWorkspace")),
        KeyBinding::new("cmd-shift-p", PauseSelectedTask, Some("DownloadWorkspace")),
        KeyBinding::new("cmd-shift-r", ResumeSelectedTask, Some("DownloadWorkspace")),
        KeyBinding::new("cmd-alt-r", RetrySelectedTask, Some("DownloadWorkspace")),
        KeyBinding::new("f2", OpenTaskOutputName, Some("DownloadWorkspace")),
        KeyBinding::new("delete", RemoveSelectedTask, Some("DownloadWorkspace")),
        KeyBinding::new("escape", CloseTaskOutputName, Some("TaskOutputNameDialog")),
        KeyBinding::new("enter", SubmitTaskOutputName, Some("TaskOutputNameDialog")),
        KeyBinding::new(
            "cmd-enter",
            SubmitTaskOutputName,
            Some("TaskOutputNameDialog"),
        ),
        KeyBinding::new("escape", CloseBatchFailures, Some("BatchFailureDialog")),
        KeyBinding::new("cmd-,", OpenSettings, Some("DownloadWorkspace")),
        KeyBinding::new("escape", CloseSettings, Some("SettingsPage")),
        KeyBinding::new("cmd-enter", SaveSettings, Some("SettingsPage")),
        KeyBinding::new("backspace", Backspace, Some("SettingsDirectoryInput")),
        KeyBinding::new("delete", Delete, Some("SettingsDirectoryInput")),
        KeyBinding::new("left", MoveLeft, Some("SettingsDirectoryInput")),
        KeyBinding::new("right", MoveRight, Some("SettingsDirectoryInput")),
        KeyBinding::new("shift-left", SelectLeft, Some("SettingsDirectoryInput")),
        KeyBinding::new("shift-right", SelectRight, Some("SettingsDirectoryInput")),
        KeyBinding::new("secondary-a", SelectAll, Some("SettingsDirectoryInput")),
        KeyBinding::new("home", MoveHome, Some("SettingsDirectoryInput")),
        KeyBinding::new("end", MoveEnd, Some("SettingsDirectoryInput")),
        KeyBinding::new("secondary-v", Paste, Some("SettingsDirectoryInput")),
        KeyBinding::new("secondary-x", Cut, Some("SettingsDirectoryInput")),
        KeyBinding::new("secondary-c", Copy, Some("SettingsDirectoryInput")),
        KeyBinding::new("tab", FocusNext, None),
        KeyBinding::new("shift-tab", FocusPrevious, None),
    ]);
}
